### ISSUE TITLE
Stuck on login page

### ISSUE THREAD

**Issue by iamalexblue** [aoaostar/drcom_tools#1]
I've tried web and local versions, sadly it can not work either. 

it always stuck on login page

**Comment by aoaostar** [comment]
注意你的登录接口地址是不是跟我的一样，    
https://github.com/aoaostar/drcom_tools/blob/1e6ec8f91cb210c7dfd60407d15008148e324b25/static/app.js#L178-L181

**Comment by iamalexblue** [comment]
内个，该怎么看呢？ 代码小白（电脑系统为 Mac OS）

**Comment by aoaostar** [comment]
你连接WiFi后会跳出认证界面，你看看你的那个认证界面的ip是多少，改一下就行了

**Comment by aoaostar** [comment]
![image](https://user-images.githubusercontent.com/86001674/133757214-713a36e8-b6ed-4d07-a04d-a85632faf323.png)
OK ,加了个ip配置
https://github.com/aoaostar/drcom_tools/commit/ec97206013134de630c34216d7e276bbfdbcc0b4

**Comment by iamalexblue** [comment]
> ![image](https://user-images.githubusercontent.com/86001674/133757214-713a36e8-b6ed-4d07-a04d-a85632faf323.png)
> OK ,加了个ip配置
> [ec97206](https://github.com/aoaostar/drcom_tools/commit/ec97206013134de630c34216d7e276bbfdbcc0b4)

哇太棒了吧。 刚才有点忙没回复，多谢啦。我回去再试试🤗

**Comment by iamalexblue** [comment]
> ![image](https://user-images.githubusercontent.com/86001674/133757214-713a36e8-b6ed-4d07-a04d-a85632faf323.png)
> OK , 加了个 ip 配置
> [ec97206](https://github.com/aoaostar/drcom_tools/commit/ec97206013134de630c34216d7e276bbfdbcc0b4)

呜呜 不知道是不是我使用方式有问题，我在 Win 和 Mac 上测试之后发现都是卡在登录界面，无法正常登录，认证系统地址我确定是正确的，但就是无法登录（如图所示）

![image](https://user-images.githubusercontent.com/41639269/133802762-fbeee0ab-8631-42a1-aa73-a25f408f4e81.png)

**Comment by aoaostar** [comment]
> > ![image](https://user-images.githubusercontent.com/86001674/133757214-713a36e8-b6ed-4d07-a04d-a85632faf323.png)
> > OK , 加了个 ip 配置
> > [ec97206](https://github.com/aoaostar/drcom_tools/commit/ec97206013134de630c34216d7e276bbfdbcc0b4)
> 
> 呜呜 不知道是不是我使用方式有问题，我在 Win 和 Mac 上测试之后发现都是卡在登录界面，无法正常登录，认证系统地址我确定是正确的，但就是无法登录（如图所示）
> 
> ![image](https://user-images.githubusercontent.com/41639269/133802762-fbeee0ab-8631-42a1-aa73-a25f408f4e81.png)

兄弟，你这个是公网IP，还是网吧。。。
我这个仅支持哆点校园的校园网，正常来说认证界面应该是个局域网IP了

**Comment by iamalexblue** [comment]
> > > ![image](https://user-images.githubusercontent.com/86001674/133757214-713a36e8-b6ed-4d07-a04d-a85632faf323.png)
> > > OK , 加了个 ip 配置
> > > [ec97206](https://github.com/aoaostar/drcom_tools/commit/ec97206013134de630c34216d7e276bbfdbcc0b4)
> > 
> > 
> > 呜呜 不知道是不是我使用方式有问题，我在 Win 和 Mac 上测试之后发现都是卡在登录界面，无法正常登录，认证系统地址我确定是正确的，但就是无法登录（如图所示）
> > ![image](https://user-images.githubusercontent.com/41639269/133802762-fbeee0ab-8631-42a1-aa73-a25f408f4e81.png)
> 
> 兄弟，你这个是公网IP，还是网吧。。。
> 我这个仅支持哆点校园的校园网，正常来说认证界面应该是个局域网IP了

- 淦 垃圾学校😂不让web端登录，必须得下载那个客户端才让用，然后还巨难用。既然这样的话多谢解答了，close 这个 issue 吧
